name: docker-image-push-join

on:
  push:
    branches: [ main ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current date # get the date of the build
      id: date
      run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_OUTPUT"

    - name: Run a one-line script
      run: echo running in repo ${GITHUB_REPOSITORY#*/} branch ${GITHUB_REF##*/} on ${{ steps.date.outputs.date }}

    - name: build docker image
      run: |
        docker build -t $DOCKER_USER/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/}_${{ steps.date.outputs.date }} ./frontend
        docker images

    - name: push docker image
      run: |
        docker push $DOCKER_USER/${GITHUB_REPOSITORY#*/}:${GITHUB_REF##*/}_${{ steps.date.outputs.date }}

    - name: Create artifact text file
      run: |
          echo ${{ steps.date.outputs.date }} > join_page_tag_file.txt
          echo "Created tag text file"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: join-page-image-tag
          path: join_page_tag_file.txt
          overwrite: true
